FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

# Install SQL Server tools
RUN apt-get update && apt-get install -y curl gnupg2
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update 
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

COPY sqlserver-init/init-db.sh /init-db.sh
RUN chmod +x /init-db.sh

USER mssql

CMD ["/init-db.sh"]