version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: nntruong112/back-end-sqlserver:latest
    container_name: sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AimToTheStar@123
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - spring-network
    restart: unless-stopped

  # Spring Boot Application
  spring-app:
    image: nntruong112/back-end-spring-app:latest
    container_name: spring-boot-app
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=adn_test_system;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=AimToTheStar@123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServerDialect
    networks:
      - spring-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  spring-network:
    driver: bridge